version: "2"
services:
  www:
    build: .
    command: npm run-script dev
    environment:
      WS_URL:
    ports:
      - '80:3000'
    volumes:
      - .:/home/app
      - /home/app/node_modules
      - /home/app/public/vendor
